import { createDaysOfWeek } from './calendar/render-week.js';
import { renderCalendar } from './calendar/render-calendar.js';
import { renderSidebar } from './calendar/sidebar.js';
import { displayCurrentWeek, switchWeekForward } from './calendar/render-current-week.js';
import { closePopup, createPopup } from './calendar/create-popup.js';
import { renderEvents } from './calendar/render-events.js';
// import { durationValidation } from './validating-form.js';
import { editSaveHandler } from './calendar/save-event.js';
import { deleteEv } from './calendar/delete-event.js';
import { durationValidation } from './calendar/validating-form.js';
import { renderRedLine } from './calendar/redline.js';
import './index.scss';